# Generated by Django 5.2.17 on 2026-10-02 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('term', models.PositiveIntegerField()),
                ('code', models.CharField(blank=True, max_length=32)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='academics.professor')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='academics.section')),
            ],
            options={
                'ordering': ('section__order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('section', 'title', 'professor', 'term'), name='unique_lesson_section_title_professor_term')],
            },
        ),
    ]
